### ISSUE TITLE
Cannot build with pypy from Ubuntu 16.04

### ISSUE THREAD

**Issue by living180** [benhoyt/scandir#76]
I have a pypy virtualenv on Ubuntu 16.04:

    $ python --version
    Python 2.7.3 (2.2.1+dfsg-1ubuntu0.3, Sep 30 2015, 15:18:40)
    [PyPy 2.2.1 with GCC 4.8.4]

If I try to run `pip install scandir` within that virtualenv, I get the following errors:

    cc -O2 -fPIC -Wimplicit -I/home/dharding/.virtualenvs/pcpartpicker-pypy/include -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
    _scandir.c:125:35: warning: ‘struct stat’ declared inside parameter list [enabled by default]
     #       define STRUCT_STAT struct stat
                                       ^
    _scandir.c:549:24: note: in expansion of macro ‘STRUCT_STAT’
     _pystat_fromstructstat(STRUCT_STAT *st)
                            ^
    _scandir.c:125:35: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
     #       define STRUCT_STAT struct stat
                                       ^
    _scandir.c:549:24: note: in expansion of macro ‘STRUCT_STAT’
     _pystat_fromstructstat(STRUCT_STAT *st)
                            ^
    In file included from _scandir.c:15:0:
    _scandir.c: In function ‘_pystat_fromstructstat’:
    _scandir.c:556:61: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 0, PyLong_FromLong((long)st->st_mode));
                                                                 ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:561:61: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 1, PyLong_FromLong((long)st->st_ino));
                                                                 ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:566:55: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 2, _PyLong_FromDev(st->st_dev));
                                                           ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:568:61: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 3, PyLong_FromLong((long)st->st_nlink));
                                                                 ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:573:55: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 4, _PyLong_FromUid(st->st_uid));
                                                           ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:574:55: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 5, _PyLong_FromGid(st->st_gid));
                                                           ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:580:55: error: dereferencing pointer to incomplete type
         PyStructSequence_SET_ITEM(v, 6, PyLong_FromLong(st->st_size));
                                                           ^
    /home/dharding/.virtualenvs/pcpartpicker-pypy/include/structseq.h:36:44: note: in definition of macro ‘PyStructSequence_SET_ITEM’
      (((PyStructSequence *)(op))->ob_item[i] = v)
                                                ^
    _scandir.c:598:23: error: dereferencing pointer to incomplete type
         fill_time(v, 7, st->st_atime, ansec);
                           ^
    _scandir.c:599:23: error: dereferencing pointer to incomplete type
         fill_time(v, 8, st->st_mtime, mnsec);
                           ^
    _scandir.c:600:23: error: dereferencing pointer to incomplete type
         fill_time(v, 9, st->st_ctime, cnsec);
                           ^
    _scandir.c: In function ‘path_error’:
    _scandir.c:885:5: warning: implicit declaration of function ‘PyErr_SetFromErrnoWithFilenameObject’ [-Wimplicit-function-declaration]
         return PyErr_SetFromErrnoWithFilenameObject(PyExc_OSError, path->object);
         ^
    _scandir.c:885:5: warning: return makes pointer from integer without a cast [enabled by default]
    _scandir.c: In function ‘DirEntry_fetch_stat’:
    _scandir.c:971:28: error: storage size of ‘st’ isn’t known
         struct _Py_stat_struct st;
                                ^
    _scandir.c:1009:9: warning: implicit declaration of function ‘stat’ [-Wimplicit-function-declaration]
             result = STAT(path, &st);
             ^
    _scandir.c:1011:9: warning: implicit declaration of function ‘lstat’ [-Wimplicit-function-declaration]
             result = LSTAT(path, &st);
             ^
    _scandir.c:1015:9: warning: return makes pointer from integer without a cast [enabled by default]
             return PyErr_SetFromErrnoWithFilenameObject(PyExc_OSError, self->path);
             ^
    _scandir.c: In function ‘DirEntry_test_mode’:
    _scandir.c:1114:26: error: ‘S_IFMT’ undeclared (first use in this function)
             result = (mode & S_IFMT) == mode_bits;
                              ^
    _scandir.c:1114:26: note: each undeclared identifier is reported only once for each function it appears in
    In file included from /home/dharding/.virtualenvs/pcpartpicker-pypy/include/Python.h:92:0,
                     from _scandir.c:14:
    _scandir.c:1122:29: error: ‘S_IFDIR’ undeclared (first use in this function)
             assert(mode_bits == S_IFDIR || mode_bits == S_IFREG);
                                 ^
    _scandir.c:1122:53: error: ‘S_IFREG’ undeclared (first use in this function)
             assert(mode_bits == S_IFDIR || mode_bits == S_IFREG);
                                                         ^
    _scandir.c: In function ‘DirEntry_is_dir’:
    _scandir.c:1166:57: error: ‘S_IFDIR’ undeclared (first use in this function)
         return DirEntry_py_test_mode(self, follow_symlinks, S_IFDIR);
                                                             ^
    _scandir.c: In function ‘DirEntry_is_file’:
    _scandir.c:1178:57: error: ‘S_IFREG’ undeclared (first use in this function)
         return DirEntry_py_test_mode(self, follow_symlinks, S_IFREG);
                                                             ^
    error: command 'cc' failed with exit status 1

I was able to fix this by adding

    #include <sys.stat.h>

to `_scandir.c`.

**Comment by benhoyt** [comment]
I can't reproduce this. It builds and works fine for me on PyPy -- though admittedly I'm no a newer version of PyPy (Python 2.7.10 / PyPy 5.4.1 on Ubuntu 16.10). Are you able to update your version of PyPy and try again?

It's *probably* safe to add that `#include` on all systems, but I'm a bit hesitant without testing them all.

**Comment by living180** [comment]
I can try using the pypy PPA to get the latest version, since the system I am targeting cannot be upgraded from 16.04 as that is a LTS release.  It looks like pypy started including `sys/stat.h` in [315da51498e734297881c2b6ba707abf91e7e086](https://bitbucket.org/pypy/pypy/commits/315da51498e734297881c2b6ba707abf91e7e086), which was first released in version 2.3.0.

**Comment by living180** [comment]
Feel free to close this if you like - it was simple for me to work around even using the pypy included with 16.04.  I more reported it to help anyone else who might hit the same issue.

**Comment by benhoyt** [comment]
Sounds good, thanks. I'll close this seeing PyPy have added this on their end (the issue will still be searchable though).
